import { Todo, Goal } from '@/types';

export const initialTodos: Omit<Todo, 'id' | 'createdAt' | 'updatedAt' | 'subtasks'>[] = [
  {
    title: 'Publier un post LinkedIn sur mes services',
    description: 'Partager une success story client pour attirer de nouveaux prospects',
    priority: 'HIGH',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 2 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Repondre aux messages Instagram',
    description: 'Verifier les DMs et repondre aux demandes de collaboration',
    priority: 'HIGH',
    platform: 'INSTAGRAM',
    dueDate: new Date(Date.now() + 1 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Optimiser mon profil Malt',
    description: 'Mettre a jour portfolio et tarifs',
    priority: 'MEDIUM',
    platform: 'MALT',
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Creer du contenu video pour TikTok',
    description: 'Filmer 3 videos courtes sur les coulisses du freelancing',
    priority: 'MEDIUM',
    platform: 'TIKTOK',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Analyser les statistiques de la semaine',
    description: 'Revoir engagement, portee et conversions sur toutes les plateformes',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Envoyer 5 propositions sur Upwork',
    description: 'Cibler des projets en marketing digital et gestion reseaux sociaux',
    priority: 'HIGH',
    platform: 'UPWORK',
    dueDate: new Date(Date.now() + 6 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Planifier posts Twitter de la semaine',
    description: 'Preparer 10 tweets sur tips freelance et actualites marketing',
    priority: 'MEDIUM',
    platform: 'TWITTER',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Follow-up client potentiel - Startup Tech',
    description: 'Relancer la lead qualifiee de la semaine derniere',
    priority: 'HIGH',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 12 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Creer un reel Instagram',
    description: 'Montrer mon setup de travail et outils favoris',
    priority: 'MEDIUM',
    platform: 'INSTAGRAM',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Mettre a jour portfolio Fiverr',
    description: 'Ajouter 3 nouveaux projets recents avec screenshots',
    priority: 'LOW',
    platform: 'FIVERR',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Participer a 3 discussions LinkedIn',
    description: 'Commenter sur posts de mon reseau pour augmenter visibilite',
    priority: 'MEDIUM',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 8 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Enregistrer podcast YouTube',
    description: 'Episode sur "Comment trouver ses premiers clients en freelance"',
    priority: 'LOW',
    platform: 'YOUTUBE',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Organiser webinaire gratuit',
    description: 'Planifier session live sur strategie reseaux sociaux',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Repondre aux reviews Freelancer.com',
    description: 'Remercier clients pour feedbacks positifs',
    priority: 'LOW',
    platform: 'FREELANCER',
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Preparer newsletter mensuelle',
    description: 'Compiler tips, success stories et offres du mois',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Créer carrousel LinkedIn educatif',
    description: '10 slides sur "Erreurs a eviter en freelance marketing"',
    priority: 'MEDIUM',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Stories Instagram quotidiennes',
    description: 'Partager tips quotidiens et behind-the-scenes pendant 7 jours',
    priority: 'LOW',
    platform: 'INSTAGRAM',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Networking virtuel',
    description: 'Contacter 10 nouveaux freelances pour collaborations potentielles',
    priority: 'MEDIUM',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    completed: false,
  },
];

export const initialGoals: Omit<Goal, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // LinkedIn
  {
    title: 'LinkedIn: +500 Connexions',
    description: 'Atteindre 500 nouvelles connexions qualifiées',
    category: 'LINKEDIN',
    currentValue: 0,
    targetValue: 500,
    unit: 'connexions',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), // 3 mois
    completed: false,
  },
  {
    title: 'LinkedIn: 1500 Profile Views/mois',
    description: 'Augmenter visibilité profil',
    category: 'LINKEDIN',
    currentValue: 0,
    targetValue: 1500,
    unit: 'vues',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'LinkedIn: 15 Leads Qualifiés/mois',
    description: 'Générer leads via InMail et posts',
    category: 'LINKEDIN',
    currentValue: 0,
    targetValue: 15,
    unit: 'leads',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },

  // TikTok
  {
    title: 'TikTok: 3000 Followers',
    description: 'Construire audience tech creator',
    category: 'TIKTOK',
    currentValue: 0,
    targetValue: 3000,
    unit: 'followers',
    targetDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000), // 6 mois
    completed: false,
  },
  {
    title: 'TikTok: 5000 Vues/vidéo (moyenne)',
    description: 'Améliorer reach vidéos',
    category: 'TIKTOK',
    currentValue: 0,
    targetValue: 5000,
    unit: 'vues',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },

  // Instagram
  {
    title: 'Instagram: 2000 Followers',
    description: 'Développer présence dev',
    category: 'INSTAGRAM',
    currentValue: 0,
    targetValue: 2000,
    unit: 'followers',
    targetDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Instagram: 3000 Reach/post',
    description: 'Augmenter portée publications',
    category: 'INSTAGRAM',
    currentValue: 0,
    targetValue: 3000,
    unit: 'reach',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },

  // Business
  {
    title: '6 Clients Signés',
    description: 'Convertir leads en clients payants',
    category: 'BUSINESS',
    currentValue: 0,
    targetValue: 6,
    unit: 'clients',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: '30 Leads Qualifiés',
    description: 'Pipeline de prospects chauds',
    category: 'BUSINESS',
    currentValue: 0,
    targetValue: 30,
    unit: 'leads',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },

  // Content
  {
    title: '50+ Posts LinkedIn',
    description: 'Contenu régulier de qualité',
    category: 'CONTENT',
    currentValue: 0,
    targetValue: 50,
    unit: 'posts',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: '180+ Vidéos TikTok/IG',
    description: '2 vidéos/jour pendant 3 mois',
    category: 'CONTENT',
    currentValue: 0,
    targetValue: 180,
    unit: 'vidéos',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },

  // Facebook
  {
    title: 'Facebook: 20 Groupes Actifs',
    description: 'Rejoindre et être actif dans groupes pertinents',
    category: 'FACEBOOK',
    currentValue: 0,
    targetValue: 20,
    unit: 'groupes',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    completed: false,
  },
];
