import { Todo, Goal } from '@/types';

export const initialTodos: Omit<Todo, 'id' | 'createdAt' | 'updatedAt' | 'subtasks'>[] = [
  {
    title: 'Publier un post LinkedIn sur mes services',
    description: 'Partager une success story client pour attirer de nouveaux prospects',
    priority: 'HIGH',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 2 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Repondre aux messages Instagram',
    description: 'Verifier les DMs et repondre aux demandes de collaboration',
    priority: 'HIGH',
    platform: 'INSTAGRAM',
    dueDate: new Date(Date.now() + 1 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Optimiser mon profil Malt',
    description: 'Mettre a jour portfolio et tarifs',
    priority: 'MEDIUM',
    platform: 'MALT',
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Creer du contenu video pour TikTok',
    description: 'Filmer 3 videos courtes sur les coulisses du freelancing',
    priority: 'MEDIUM',
    platform: 'TIKTOK',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Analyser les statistiques de la semaine',
    description: 'Revoir engagement, portee et conversions sur toutes les plateformes',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Envoyer 5 propositions sur Upwork',
    description: 'Cibler des projets en marketing digital et gestion reseaux sociaux',
    priority: 'HIGH',
    platform: 'UPWORK',
    dueDate: new Date(Date.now() + 6 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Planifier posts Twitter de la semaine',
    description: 'Preparer 10 tweets sur tips freelance et actualites marketing',
    priority: 'MEDIUM',
    platform: 'TWITTER',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Follow-up client potentiel - Startup Tech',
    description: 'Relancer la lead qualifiee de la semaine derniere',
    priority: 'HIGH',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 12 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Creer un reel Instagram',
    description: 'Montrer mon setup de travail et outils favoris',
    priority: 'MEDIUM',
    platform: 'INSTAGRAM',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Mettre a jour portfolio Fiverr',
    description: 'Ajouter 3 nouveaux projets recents avec screenshots',
    priority: 'LOW',
    platform: 'FIVERR',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Participer a 3 discussions LinkedIn',
    description: 'Commenter sur posts de mon reseau pour augmenter visibilite',
    priority: 'MEDIUM',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 8 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Enregistrer podcast YouTube',
    description: 'Episode sur "Comment trouver ses premiers clients en freelance"',
    priority: 'LOW',
    platform: 'YOUTUBE',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Organiser webinaire gratuit',
    description: 'Planifier session live sur strategie reseaux sociaux',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Repondre aux reviews Freelancer.com',
    description: 'Remercier clients pour feedbacks positifs',
    priority: 'LOW',
    platform: 'FREELANCER',
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Preparer newsletter mensuelle',
    description: 'Compiler tips, success stories et offres du mois',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Créer carrousel LinkedIn educatif',
    description: '10 slides sur "Erreurs a eviter en freelance marketing"',
    priority: 'MEDIUM',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Stories Instagram quotidiennes',
    description: 'Partager tips quotidiens et behind-the-scenes pendant 7 jours',
    priority: 'LOW',
    platform: 'INSTAGRAM',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    title: 'Networking virtuel',
    description: 'Contacter 10 nouveaux freelances pour collaborations potentielles',
    priority: 'MEDIUM',
    platform: 'LINKEDIN',
    dueDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    completed: false,
  },
];

export const initialGoals: Omit<Goal, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Atteindre 10K followers LinkedIn',
    description: 'Croissance organique via contenu de qualite et engagement actif',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    progress: 45,
    completed: false,
  },
  {
    title: 'Generer 5000€ MRR en freelance',
    description: 'Revenu mensuel recurrent via clients retainer',
    targetDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    progress: 60,
    completed: false,
  },
  {
    title: 'Lancer formation en ligne',
    description: 'Cours complet "Marketing Freelance de A a Z"',
    targetDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
    progress: 25,
    completed: false,
  },
  {
    title: 'Obtenir Top Rated sur Upwork',
    description: 'Maintenir 100% job success score et completeness rating',
    targetDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    progress: 70,
    completed: false,
  },
  {
    title: 'Publier 100 posts de qualite',
    description: 'Contenu educatif sur toutes plateformes sociales',
    targetDate: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
    progress: 35,
    completed: false,
  },
  {
    title: 'Construire portfolio de 20 cas clients',
    description: 'Success stories detaillees avec resultats mesurables',
    targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    progress: 40,
    completed: false,
  },
  {
    title: 'Etablir 3 partenariats strategiques',
    description: 'Collaborations long-terme avec agences et marques',
    targetDate: new Date(Date.now() + 80 * 24 * 60 * 60 * 1000),
    progress: 20,
    completed: false,
  },
];
