import { PostTemplate } from '@/types';

export const postTemplates: PostTemplate[] = [
  {
    id: '1',
    title: 'Success Story Client',
    category: 'Testimonial',
    content: `🎯 [CLIENT NAME] a multiplie son engagement par [X]!\n\nLe defi:\n[Probleme initial du client]\n\nLa solution:\n[Votre approche strategique]\n\nLes resultats:\n✅ [Metrique 1]\n✅ [Metrique 2]\n✅ [Metrique 3]\n\n💡 Cle du succes: [Insight principal]\n\n#freelance #marketing #successstory`,
    platforms: ['LINKEDIN', 'INSTAGRAM', 'FACEBOOK'],
    tags: ['testimonial', 'results', 'case-study'],
  },
  {
    id: '2',
    title: 'Tip Rapide du Jour',
    category: 'Educational',
    content: `💡 Tip Marketing du jour:\n\n[Votre conseil actionnable]\n\nPourquoi ca marche?\n[Explication breve]\n\nComment l'appliquer:\n1. [Etape 1]\n2. [Etape 2]\n3. [Etape 3]\n\nSauvegardez pour plus tard! 📌\n\n#marketingtips #digitalmarketing #freelancetips`,
    platforms: ['TWITTER', 'LINKEDIN', 'INSTAGRAM'],
    tags: ['tips', 'education', 'quick-win'],
  },
  {
    id: '3',
    title: 'Behind the Scenes',
    category: 'Personal',
    content: `📸 Ma journee type de freelance:\n\n7h00 - [Activite matinale]\n9h00 - [Travail client]\n12h00 - [Pause/Networking]\n14h00 - [Creation contenu]\n17h00 - [Admin/Prospection]\n\nLa realite du freelancing? C'est [votre verite].\n\nQu'est-ce qui ressemble a votre journee? 👇\n\n#freelancelife #entrepreneur #workfromanywhere`,
    platforms: ['INSTAGRAM', 'TIKTOK', 'LINKEDIN'],
    tags: ['personal', 'lifestyle', 'authenticity'],
  },
  {
    id: '4',
    title: 'Question Engagement',
    category: 'Engagement',
    content: `🤔 Question pour vous:\n\n[Votre question provocante ou pertinente]\n\nOption A: [Choix 1]\nOption B: [Choix 2]\n\nDites-moi en commentaire et expliquez pourquoi!\n\nPas de bonne ou mauvaise reponse - juste curieux de vos experiences 👇\n\n#community #discussion #freelancecommunity`,
    platforms: ['LINKEDIN', 'TWITTER', 'FACEBOOK'],
    tags: ['engagement', 'question', 'community'],
  },
  {
    id: '5',
    title: 'Carrousel Educatif',
    category: 'Educational',
    content: `📚 [TITRE ACCROCHEUR]\n\nVoici les [X] points essentiels:\n\n1️⃣ [Point 1 + explication]\n\n2️⃣ [Point 2 + explication]\n\n3️⃣ [Point 3 + explication]\n\n4️⃣ [Point 4 + explication]\n\n5️⃣ [Point 5 + explication]\n\nSwipe pour tout voir →\nSauvegarde si utile! 🔖\n\n#education #marketing #freelance`,
    platforms: ['INSTAGRAM', 'LINKEDIN'],
    tags: ['carousel', 'education', 'value'],
  },
  {
    id: '6',
    title: 'Annonce Service',
    category: 'Promotional',
    content: `🚀 NOUVEAU SERVICE DISPONIBLE\n\n[Nom du service]\n\nIdeal pour:\n✅ [Type de client 1]\n✅ [Type de client 2]\n✅ [Type de client 3]\n\nCe qui est inclus:\n📌 [Livrable 1]\n📌 [Livrable 2]\n📌 [Livrable 3]\n\nInteresse? Envoyez-moi un DM pour discuter! 💬\n\n#freelanceservices #marketing #socialmedia`,
    platforms: ['LINKEDIN', 'TWITTER', 'INSTAGRAM'],
    tags: ['promotional', 'service', 'offer'],
  },
  {
    id: '7',
    title: 'Statistiques Impressionnantes',
    category: 'Data',
    content: `📊 Chiffres cles du mois:\n\n📈 [Metrique 1]: +[X]%\n🎯 [Metrique 2]: [Nombre]\n💰 [Metrique 3]: [Montant]\n👥 [Metrique 4]: [Statistique]\n\nCe qui a fait la difference:\n[Votre strategie ou action cle]\n\nLa croissance est possible avec [principe].\n\n#growth #stats #digitalmarketing`,
    platforms: ['LINKEDIN', 'TWITTER', 'INSTAGRAM'],
    tags: ['data', 'results', 'growth'],
  },
  {
    id: '8',
    title: 'Erreurs a Eviter',
    category: 'Educational',
    content: `🚫 [X] Erreurs que j'ai faites en freelance\n\n(Pour que vous ne les fassiez pas)\n\n❌ Erreur #1: [Description]\n→ Solution: [Conseil]\n\n❌ Erreur #2: [Description]\n→ Solution: [Conseil]\n\n❌ Erreur #3: [Description]\n→ Solution: [Conseil]\n\nApprenez de mes erreurs! 💡\n\n#freelancemistakes #lessons #entrepreneurship`,
    platforms: ['LINKEDIN', 'INSTAGRAM', 'TWITTER'],
    tags: ['mistakes', 'lessons', 'education'],
  },
  {
    id: '9',
    title: 'Tool Recommendation',
    category: 'Resources',
    content: `🛠️ Mon outil prefere: [NOM OUTIL]\n\nPourquoi je l'adore:\n\n⭐ [Avantage 1]\n⭐ [Avantage 2]\n⭐ [Avantage 3]\n\nParfait pour:\n[Type de tache ou probleme resolu]\n\nPrix: [Gratuit/Payant]\n\nVous l'utilisez deja? Quel est votre verdict? 👇\n\n#tools #productivity #freelancetools`,
    platforms: ['TWITTER', 'LINKEDIN', 'INSTAGRAM'],
    tags: ['tools', 'resources', 'recommendation'],
  },
  {
    id: '10',
    title: 'Client Testimonial',
    category: 'Testimonial',
    content: `💬 Ce que mes clients disent:\n\n"[Citation testimonial client]"\n\n- [Nom], [Poste] @ [Entreprise]\n\n🎯 Projet: [Breve description]\n📈 Resultat: [Metrique cle]\n\nRien ne vaut la satisfaction client! 🙏\n\nBesoin d'aide similaire? Parlons-en en DM.\n\n#testimonial #clientsuccess #freelance`,
    platforms: ['LINKEDIN', 'INSTAGRAM', 'FACEBOOK'],
    tags: ['testimonial', 'social-proof', 'results'],
  },
  {
    id: '11',
    title: 'Weekly Recap',
    category: 'Personal',
    content: `📅 Ma semaine en chiffres:\n\n📝 [X] projets clients completes\n✉️ [X] nouveaux prospects contactes\n📱 [X] posts publies\n☕ [X] cafes bus\n\nHighlight de la semaine:\n[Votre moment fort]\n\nObjectif semaine prochaine:\n[Votre prochain objectif]\n\n#weeklyrecap #freelancelife #productivity`,
    platforms: ['INSTAGRAM', 'TWITTER', 'LINKEDIN'],
    tags: ['recap', 'personal', 'transparency'],
  },
  {
    id: '12',
    title: 'Before/After',
    category: 'Results',
    content: `⚡ AVANT vs APRES\n\nAVANT:\n❌ [Situation negative 1]\n❌ [Situation negative 2]\n❌ [Situation negative 3]\n\nAPRES:\n✅ [Resultat positif 1]\n✅ [Resultat positif 2]\n✅ [Resultat positif 3]\n\nLa transformation est possible.\nVoulez-vous les memes resultats? 🚀\n\n#transformation #beforeafter #results`,
    platforms: ['INSTAGRAM', 'LINKEDIN', 'FACEBOOK'],
    tags: ['transformation', 'results', 'comparison'],
  },
  {
    id: '13',
    title: 'Myth Busting',
    category: 'Educational',
    content: `🔥 MYTHE vs REALITE\n\nMythe: [Croyance populaire fausse]\n\nRealite: [La verite]\n\nPourquoi ce mythe persiste?\n[Votre explication]\n\nLa verite c'est que [votre conclusion].\n\nD'autres mythes a debunker? Commentez! 👇\n\n#mythbusting #truth #freelancereality`,
    platforms: ['TWITTER', 'LINKEDIN', 'INSTAGRAM'],
    tags: ['myths', 'education', 'truth'],
  },
  {
    id: '14',
    title: 'Motivation Monday',
    category: 'Motivational',
    content: `💪 Lundi Motivation\n\n"[Citation inspirante]"\n\nCette semaine, je me concentre sur:\n\n🎯 [Objectif 1]\n🎯 [Objectif 2]\n🎯 [Objectif 3]\n\nEt vous? Quels sont vos objectifs cette semaine?\n\nOn se motive ensemble! 🔥\n\n#mondaymotivation #goals #freelancegoals`,
    platforms: ['INSTAGRAM', 'LINKEDIN', 'TWITTER'],
    tags: ['motivation', 'goals', 'inspiration'],
  },
  {
    id: '15',
    title: 'Quick Poll',
    category: 'Engagement',
    content: `📊 SONDAGE RAPIDE\n\n[Votre question]\n\n🔵 Option A\n🟢 Option B\n🟡 Option C\n🔴 Option D\n\nVotez et dites pourquoi en commentaire!\n\nCurieux de voir les resultats 👀\n\n#poll #community #engagement`,
    platforms: ['TWITTER', 'LINKEDIN', 'INSTAGRAM'],
    tags: ['poll', 'engagement', 'interactive'],
  },
  {
    id: '16',
    title: 'Industry News Commentary',
    category: 'News',
    content: `📰 [TITRE ACTUALITE]\n\nCe qui s'est passe:\n[Resume bref]\n\nMon analyse:\n[Votre opinion/insight]\n\nImpact pour les freelances:\n[Implications pratiques]\n\nVotre avis? 💭\n\n#news #industry #digitalmarketing`,
    platforms: ['LINKEDIN', 'TWITTER'],
    tags: ['news', 'analysis', 'industry'],
  },
  {
    id: '17',
    title: 'Resource List',
    category: 'Resources',
    content: `📚 Mes [X] ressources favorites\n\n1. [Ressource 1] - [Breve description]\n2. [Ressource 2] - [Breve description]\n3. [Ressource 3] - [Breve description]\n4. [Ressource 4] - [Breve description]\n5. [Ressource 5] - [Breve description]\n\nToutes gratuites! 💰\n\nSauvegardez ce post pour y revenir! 🔖\n\n#resources #free #freelanceresources`,
    platforms: ['LINKEDIN', 'TWITTER', 'INSTAGRAM'],
    tags: ['resources', 'list', 'value'],
  },
  {
    id: '18',
    title: 'Challenge Announcement',
    category: 'Engagement',
    content: `🎯 CHALLENGE [NOM]\n\nPendant [X] jours, je vais:\n[Description du challenge]\n\nObjectif:\n[Ce que vous voulez accomplir]\n\nQui me rejoint? 🙋\n\nCommentez "IN" et je vous ajoute!\n\nOn commence [date]! 🚀\n\n#challenge #community #growth`,
    platforms: ['INSTAGRAM', 'LINKEDIN', 'TWITTER'],
    tags: ['challenge', 'engagement', 'community'],
  },
  {
    id: '19',
    title: 'FAQ Answer',
    category: 'Educational',
    content: `❓ FAQ: [Question frequente]\n\nReponse courte:\n[Reponse directe]\n\nReponse detaillee:\n[Explication approfondie]\n\nConseil pro:\n[Votre astuce bonus]\n\nD'autres questions? Posez-les en commentaire! 👇\n\n#faq #help #freelanceadvice`,
    platforms: ['LINKEDIN', 'INSTAGRAM', 'TWITTER'],
    tags: ['faq', 'education', 'help'],
  },
  {
    id: '20',
    title: 'Gratitude Post',
    category: 'Personal',
    content: `🙏 Moment reconnaissance\n\nMerci a:\n\n💙 Mes clients qui me font confiance\n💙 Ma communaute qui me soutient\n💙 [Personne/Groupe specifique]\n\nGrace a vous, j'ai pu [accomplissement recent].\n\nQui voulez-vous remercier aujourd'hui? 👇\n\n#gratitude #thankyou #community`,
    platforms: ['LINKEDIN', 'INSTAGRAM', 'FACEBOOK'],
    tags: ['gratitude', 'personal', 'community'],
  },
  {
    id: '21',
    title: 'Process Breakdown',
    category: 'Educational',
    content: `⚙️ Comment je [processus]:\n\nEtape 1: [Description + pourquoi]\nEtape 2: [Description + pourquoi]\nEtape 3: [Description + pourquoi]\nEtape 4: [Description + pourquoi]\nEtape 5: [Description + pourquoi]\n\nTemps total: [Duree]\nResultat: [Outcome]\n\nSauvegardez pour reference! 📌\n\n#process #howto #freelancetips`,
    platforms: ['LINKEDIN', 'INSTAGRAM', 'TWITTER'],
    tags: ['process', 'tutorial', 'education'],
  },
  {
    id: '22',
    title: 'Hot Take',
    category: 'Opinion',
    content: `🔥 HOT TAKE:\n\n[Votre opinion controverse mais reflechie]\n\nPourquoi je pense ca:\n\n1. [Argument 1]\n2. [Argument 2]\n3. [Argument 3]\n\nD'accord ou pas d'accord?\nDebat respectueux en commentaire 👇\n\n#hottake #opinion #discussion`,
    platforms: ['TWITTER', 'LINKEDIN'],
    tags: ['opinion', 'debate', 'discussion'],
  },
];
